export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST"
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL"


export const MY_0RDERS_REQUEST = "MY_0RDERS_REQUEST"
export const MY_0RDERS_SUCCESS = "MY_0RDERS_SUCCESS"
export const MY_0RDERS_FAIL = "MY_0RDERS_FAIL"


export const CLEAR_ERRORS = "CLEAR_ERROR"